### ISSUE TITLE
[question] It works as intended, but there's some failed messages, should I be concerned?

### ISSUE THREAD

**Issue by thesomeotherguy** [jikamens/keyless-entry#4]
First of all, this is not a bug, but merely a question.

Your tool works amazingly and is incredibly helpful. I believe it should be implemented in the official Linux itself, where the next planned and anticipated reboot could be keyless for once.

It works! By using the command `keyless-entry enable-once` the next reboot does bypasses my very long passphrase (12 words with nearly 100 alphanumeric characters), that has been a real pain because my VPS provider uses simple html noVNC, which doesn't support copy-paste. As a result, I have to type it manually and carefully. I can't access SSH until the system is up and running after the passphrase is given.

My question is, during that reboot (when bypassing the passphrase), I encountered some failed messages (attached). It states that there were some dependency failures for Cryptography Setup and Local Encrypted Volumes.

![bypass-passphrase-keyless-entry-kvm-debian-11](https://github.com/jikamens/keyless-entry/assets/112531618/a9e26549-47fb-4d4a-bb99-9d962ce49540)

Is this normal and intended as expected information?

My system is Linux Debian 11 on VPS KVM.

Many thanks.

**Comment by jikamens** [comment]
Debian quirk, you don't need to worry about it as long as the system boots successfully with the filesystem mounted.
