### ISSUE TITLE
Timestamp with added "Z" in config file causes error with datetime.datetime.fromisoformat during disable on Ubuntu 22.04.2

### ISSUE THREAD

**Issue by johnmhancock** [jikamens/keyless-entry#7]
https://github.com/jikamens/keyless-entry/blob/832bef08b743d230a3dcc5864f74624e03139cf6/keyless-entry#L454

When trying to parse the enabled_at value in /etc/keyless-entry.conf , ubuntu 22.04 generates the following error:

./keyless-entry disable
Removing key from dm_crypt-0 (UUID=xxxxxxxxxxxxx)
Traceback (most recent call last):
  File "/root/keyless-entry/./keyless-entry", line 602, in <module>
    main()
  File "/root/keyless-entry/./keyless-entry", line 598, in main
    args.func(args)
  File "/root/keyless-entry/./keyless-entry", line 497, in disable
    enabled_at = datetime.datetime.fromisoformat(
ValueError: Invalid isoformat string: '2023-07-11T15:14:24Z'

Removing the "Z" from start_time resolves this, but you may want to add/convert the timezone flag back in after reading enabled_at.

Steps to reproduce:

Clone repo on ubuntu 22.04.2 LTS

cd keyless-entry/
./keyless-entry configure
./keyless-entry enable-once
./keyless-entry disable

**Comment by jikamens** [comment]
This is an incompatibility between Python 3.11 and versions of Python prior to 3.11.

Can you please try the version of the script at https://github.com/jikamens/keyless-entry/blob/issue7/keyless-entry and see if it resolves the issue for you? I do not have the ability to test easily with older Python versions.

**Comment by alanivey** [comment]
@jikamens this works for me on Ubuntu 22.04; I no longer have the ValueError is shown by the OP. Also, this appears to solve a separate problem I had with using `enable-once` where the second reboot was in a failure loop with no prompt to enter the password. For me, I'll grab the script from the `issue7` branch until it's merged; thanks!

Given that 22.04 has Python 3.10 as the default for `/usr/bin/python3` and you mention syntax for 3.11, what's your recommended method for running this script? Install 3.11 separately and set the shebang for keyless-entry to a 3.11 binary?

**Comment by jikamens** [comment]
Thanks for testing and confirming the fix. I've merged it to main.

You can just use the default interpreter, since I've made the script compatible with 3.10 with this fix. Eventually when 3.10 is deprecated at some point several years in the future I'll remove the compatibility code.

**Comment by johnmhancock** [comment]
I tried this version and that resolved the issue for me :


keyless-entry# git checkout issue7

keyless-entry# python3 --version
Python 3.10.6

keyless-entry# ./keyless-entry enable-once
Adding key to sda3_crypt (UUID=xxxx)
update-initramfs: Generating /boot/initrd.img-5.19.0-32-generic

update-initramfs: Generating /boot/initrd.img-5.19.0-46-generic

keyless-entry# cat /etc/keyless-entry.conf
[settings]
version = 2
source0 = UUID=xxxx
target0 = sda3_crypt
configured = true
enabled = true
enabled_at = 2023-07-13T18:59:50Z

keyless-entry# ./keyless-entry disable
Removing key from sda3_crypt (UUID=XXXX)

update-initramfs: Generating /boot/initrd.img-5.19.0-32-generic

update-initramfs: Generating /boot/initrd.img-5.19.0-46-generic

keyless-entry# cat /etc/keyless-entry.conf
[settings]
version = 2
source0 = UUID=xxxx
target0 = sda3_crypt
configured = true

I still need to test some restarts but the error with timestamp went away.
