### ISSUE TITLE
datetime.utcnow() Is Now Deprecated | scheduled for removal

### ISSUE THREAD

**Issue by riker1** [jikamens/keyless-entry#9]
FYI running keyless-entry on a Ubuntu 64bit Noble machine (24.04)

[/usr/local/bin/keyless-entry:454: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. 

Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  start_time = datetime.datetime.utcnow().isoformat(timespec='seconds') + "Z"](url)

**Comment by jikamens** [comment]
Thanks, fixed.
